export const teams = [
  {
    flag: {
      big: require("./PortugalBig.svg"),
      alt: "Portugal flag",
    },
    nation: "Portugal",
    nationNick: "POR",
    eurosPlayed: 7,
    bestPlace: "Winners (1)",
    bestPlayer: "Cristiano Ronaldo",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./CroatiaBig.svg"),
      alt: "Croatia flag",
    },
    nation: "Croatia",
    nationNick: "CRO",
    eurosPlayed: 5,
    bestPlace: "QF (2)",
    bestPlayer: "Luka Modrić",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./GermanyBig.svg"),
      alt: "Germany flag",
    },
    nation: "Germany",
    nationNick: "GER",
    eurosPlayed: 12,
    bestPlace: "Winners (3)",
    bestPlayer: "Manuel Neuer",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./FranceBig.svg"),
      alt: "France flag",
    },
    nation: "France",
    nationNick: "FRA",
    eurosPlayed: 9,
    bestPlace: "Winners (2)",
    bestPlayer: "Kylian Mbappé",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./EnglandBig.svg"),
      alt: "England flag",
    },
    nation: "England",
    nationNick: "ENG",
    eurosPlayed: 9,
    bestPlace: "SF (2)",
    bestPlayer: "Harry Kane",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./ItalyBig.svg"),
      alt: "Italy flag",
    },
    nation: "Italy",
    nationNick: "ITA",
    eurosPlayed: 9,
    bestPlace: "Winners (1)",
    bestPlayer: "Ciro Immobile",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./BelgiumBig.svg"),
      alt: "Belgium flag",
    },
    nation: "Belgium",
    nationNick: "BEL",
    eurosPlayed: 5,
    bestPlace: "SF (1)",
    bestPlayer: "Kevin De Bruyne",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./NetherlandsBig.svg"),
      alt: "Netherlands flag",
    },
    nation: "Netherlands",
    nationNick: "NDE",
    eurosPlayed: 9,
    bestPlace: "Winners (1)",
    bestPlayer: "Memphis Depay",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
]
