export const teams = [
  {
    flag: {
      big: require("./PortugalBig.svg"),
      alt: "Portugal flag",
    },
    nation: "Portugal",
    nationNick: "POR",
    eurosPlayed: 7,
    bestPlace: "Winners (1)",
    bestPlayer: "Cristiano Ronaldo",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./CroatiaBig.svg"),
      alt: "Croatia flag",
    },
    nation: "Croatia",
    nationNick: "CRO",
    eurosPlayed: 5,
    bestPlace: "Quarter-finals (2)",
    bestPlayer: "Luka Modrić",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./GermanyBig.svg"),
      alt: "Germany flag",
    },
    nation: "Germany",
    nationNick: "GER",
    eurosPlayed: 12,
    bestPlace: "Winners (3)",
    bestPlayer: "Manuel Neuer",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./FranceBig.svg"),
      alt: "France flag",
    },
    nation: "France",
    nationNick: "FRA",
    eurosPlayed: 9,
    bestPlace: "Winners (2)",
    bestPlayer: "Kylian Mbappé",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./EnglandBig.svg"),
      alt: "England flag",
    },
    nation: "England",
    nationNick: "ENG",
    eurosPlayed: 9,
    bestPlace: "Semi-finals (2)",
    bestPlayer: "Harry Kane",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./ItalyBig.svg"),
      alt: "Italy flag",
    },
    nation: "Italy",
    nationNick: "ITA",
    eurosPlayed: 9,
    bestPlace: "Winners (1)",
    bestPlayer: "Ciro Immobile",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./BelgiumBig.svg"),
      alt: "Belgium flag",
    },
    nation: "Belgium",
    nationNick: "BEL",
    eurosPlayed: 5,
    bestPlace: "Semi-finals (1)",
    bestPlayer: "Kevin De Bruyne",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./NetherlandsBig.svg"),
      alt: "Netherlands flag",
    },
    nation: "Netherlands",
    nationNick: "NDE",
    eurosPlayed: 9,
    bestPlace: "Winners (1)",
    bestPlayer: "Memphis Depay",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./UkraineBig.svg"),
      alt: "Ukraine flag",
    },
    nation: "Ukraine",
    nationNick: "UKR",
    eurosPlayed: 2,
    bestPlace: "Group Stage",
    bestPlayer: "Denys Favorov",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./SwitzerlandBig.svg"),
      alt: "Switzerland flag",
    },
    nation: "Switzerland",
    nationNick: "SWI",
    eurosPlayed: 4,
    bestPlace: "Round of 16 (1)",
    bestPlayer: "Xherdan Shaqiri",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./RussiaBig.svg"),
      alt: "Russia flag",
    },
    nation: "Russia",
    nationNick: "RUS",
    eurosPlayed: 11,
    bestPlace: "Winners (1)",
    bestPlayer: "Artem Dzyuba",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
  {
    flag: {
      big: require("./PolandBig.svg"),
      alt: "Poland flag",
    },
    nation: "Poland",
    nationNick: "POL",
    eurosPlayed: 3,
    bestPlace: "Quarter-finals (1)",
    bestPlayer: "R. Lewandowski",
    score: {
      won: 0,
      drawn: 0,
      lost: 0,
      points: 0,
    },
  },
]
