export const teams = [
  {
    groupName: "A",
    groupTeams: [
      {
        flag: {
          small: require("./PortugalSmall.svg"),
          big: require("./PortugalBig.svg"),
          alt: "Portugal flag",
        },
        nation: "Portugal",
        nationNick: "POR",
        eurosPlayed: 7,
        bestPlace: "Winners (1)",
        bestPlayer: "Cristiano Ronaldo",
        score: {
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
        },
      },
      {
        flag: {
          small: require("./CroatiaSmall.svg"),
          big: require("./CroatiaBig.svg"),
          alt: "Croatia flag",
        },
        nation: "Croatia",
        nationNick: "CRO",
        eurosPlayed: 5,
        bestPlace: "Quarter-finals (2)",
        bestPlayer: "Luka Modrić",
        score: {
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
        },
      },
      {
        flag: {
          small: require("./GermanySmall.svg"),
          big: require("./GermanyBig.svg"),
          alt: "Germany flag",
        },
        nation: "Germany",
        nationNick: "GER",
        eurosPlayed: 12,
        bestPlace: "Winners (3)",
        bestPlayer: "Manuel Neuer",
        score: {
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
        },
      },
      {
        flag: {
          small: require("./FranceSmall.svg"),
          big: require("./FranceBig.svg"),
          alt: "France flag",
        },
        nation: "France",
        nationNick: "FRA",
        eurosPlayed: 9,
        bestPlace: "Winners (2)",
        bestPlayer: "Kylian Mbappé",
        score: {
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
        },
      },
    ],
  },

  {
    groupName: "B",
    groupTeams: [
      {
        flag: {
          small: require("./EnglandSmall.svg"),
          big: require("./EnglandBig.svg"),
          alt: "England flag",
        },
        nation: "England",
        nationNick: "ENG",
        eurosPlayed: 9,
        bestPlace: "Semi-finals (2)",
        bestPlayer: "Harry Kane",
        score: {
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
        },
      },
      {
        flag: {
          small: require("./ItalySmall.svg"),
          big: require("./ItalyBig.svg"),
          alt: "Italy flag",
        },
        nation: "Italy",
        nationNick: "ITA",
        eurosPlayed: 9,
        bestPlace: "Winners (1)",
        bestPlayer: "Ciro Immobile",
        score: {
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
        },
      },
      {
        flag: {
          small: require("./BelgiumSmall.svg"),
          big: require("./BelgiumBig.svg"),
          alt: "Belgium flag",
        },
        nation: "Belgium",
        nationNick: "BEL",
        eurosPlayed: 5,
        bestPlace: "Semi-finals (1)",
        bestPlayer: "Kevin De Bruyne",
        score: {
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
        },
      },
      {
        flag: {
          small: require("./NetherlandsSmall.svg"),
          big: require("./NetherlandsBig.svg"),
          alt: "Netherlands flag",
        },
        nation: "Netherlands",
        nationNick: "NLD",
        eurosPlayed: 9,
        bestPlace: "Winners (1)",
        bestPlayer: "Virgil Van Dijk",
        score: {
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
        },
      },
    ],
  },

  {
    groupName: "C",
    groupTeams: [
      {
        flag: {
          small: require("./UkraineSmall.svg"),
          big: require("./UkraineBig.svg"),
          alt: "Ukraine flag",
        },
        nation: "Ukraine",
        nationNick: "UKR",
        eurosPlayed: 2,
        bestPlace: "Group Stage",
        bestPlayer: "Denys Favorov",
        score: {
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
        },
      },
      {
        flag: {
          small: require("./SwitzerlandSmall.svg"),
          big: require("./SwitzerlandBig.svg"),
          alt: "Switzerland flag",
        },
        nation: "Switzerland",
        nationNick: "SWI",
        eurosPlayed: 4,
        bestPlace: "Round of 16 (1)",
        bestPlayer: "Xherdan Shaqiri",
        score: {
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
        },
      },
      {
        flag: {
          small: require("./RussiaSmall.svg"),
          big: require("./RussiaBig.svg"),
          alt: "Russia flag",
        },
        nation: "Russia",
        nationNick: "RUS",
        eurosPlayed: 11,
        bestPlace: "Winners (1)",
        bestPlayer: "Artem Dzyuba",
        score: {
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
        },
      },
      {
        flag: {
          small: require("./PolandSmall.svg"),
          big: require("./PolandBig.svg"),
          alt: "Poland flag",
        },
        nation: "Poland",
        nationNick: "POL",
        eurosPlayed: 3,
        bestPlace: "Quarter-finals (1)",
        bestPlayer: "R. Lewandowski",
        score: {
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
        },
      },
    ],
  },

  {
    groupName: "D",
    groupTeams: [
      {
        flag: {
          small: require("./AustriaSmall.svg"),
          big: require("./AustriaBig.svg"),
          alt: "Austria flag",
        },
        nation: "Austria",
        nationNick: "AUS",
        eurosPlayed: 2,
        bestPlace: "Group Stage",
        bestPlayer: "David Alaba",
        score: {
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
        },
      },
      {
        flag: {
          small: require("./DenmarkSmall.svg"),
          big: require("./DenmarkBig.svg"),
          alt: "Denmark flag",
        },
        nation: "Denmark",
        nationNick: "DEN",
        eurosPlayed: 7,
        bestPlace: "Winners (1)",
        bestPlayer: "Christian Eriksen",
        score: {
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
        },
      },
      {
        flag: {
          small: require("./SwedenSmall.svg"),
          big: require("./SwedenBig.svg"),
          alt: "Sweden flag",
        },
        nation: "Sweden",
        nationNick: "SWE",
        eurosPlayed: 6,
        bestPlace: "Semi-finals (1)",
        bestPlayer: "Dejan Kulusevski",
        score: {
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
        },
      },
      {
        flag: {
          small: require("./TurkeySmall.svg"),
          big: require("./TurkeyBig.svg"),
          alt: "Turkey flag",
        },
        nation: "Turkey",
        nationNick: "TUR",
        eurosPlayed: 4,
        bestPlace: "Semi-finals (1)",
        bestPlayer: "Hakan Çalhanoğlu",
        score: {
          won: 0,
          drawn: 0,
          lost: 0,
          points: 0,
        },
      },
    ],
  },
]
